services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3400:3400"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "5500:5500"
    environment:
      - PORT=5500
      - MONGO_URL=mongodb+srv://anant:anant1506@cluster0.ofeyq.mongodb.net/
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
